### ISSUE TITLE
无法修改

### ISSUE THREAD

**Issue by Hyton411** [LightAPIs/bookmark-url-batch-replacer#1]
360浏览器无法替换网址，不知道是不是权限问题？

**Comment by LightAPIs** [comment]
按照360浏览器官方社区里关于此类问题的[答复](https://bbs.360.cn/forum.php?mod=redirect&goto=findpost&ptid=16065415&pid=118912979)，是360浏览器本身不允许其他扩展程序读取、更改浏览器书签。
