### ISSUE TITLE
Feature Request: items per page

### ISSUE THREAD

**Issue by ghost** [LightAPIs/bookmark-url-batch-replacer#2]
When updating many bookmarks, it's not ideal to do them 10 at a time. A drop-down menu where you can select to preview and apply to 10, 25, 50, or 100 bookmarks at a time would be awesome.

**Comment by ghost** [comment]
Thank you! Do you have ko-fi or some such?

**Comment by LightAPIs** [comment]
> Thank you! Do you have ko-fi or some such?

https://ko-fi.com/monogamy
