### ISSUE TITLE
Feature Request: update title

### ISSUE THREAD

**Issue by gutenye** [LightAPIs/bookmark-url-batch-replacer#5]
Hey, this is a great extension. Can you also support batch updating the bookmark title? Thanks

**Comment by LightAPIs** [comment]
[tidier-bookmark-next](https://github.com/LightAPIs/tidier-bookmark-next) can handle this requirement.

**Comment by gutenye** [comment]
Thanks, I like this extension's UI to edit them. I forked your extension to meet my needs https://github.com/gutenye/bookmark-title-batch-replacer
